### ISSUE TITLE
Error with building docker image

### ISSUE THREAD

**Issue by kinal1999** [wells-wood-research/timed-design#88]
<img width="979" alt="Screenshot 2024-05-07 at 12 26 38 PM" src="https://github.com/wells-wood-research/timed-design/assets/136503460/2a38af68-55a7-4d35-8cda-51f9b1625744">

**Comment by universvm** [comment]
@kinal1999 are you using the latest version of the repo?

**Comment by universvm** [comment]
@kinal1999 I'm not sure if you are using the latest version because I believe we removed the BUDEFF dependency a while ago. I suggest you clone it again.

You don't need to add streamlit to the requirements. Please don't change anything you should be able to build as is.

**Comment by universvm** [comment]
Please use the following command after cloning 

```bash
cd timed-design
docker build --no-cache -t timed_design .
```

**Comment by kinal1999** [comment]
<img width="842" alt="Screenshot 2024-05-07 at 1 23 11 PM" src="https://github.com/wells-wood-research/timed-design/assets/136503460/ee8a2659-a6b1-4a34-bbed-0cffebcda299">

**Comment by universvm** [comment]
@kinal1999 are you able to get more information like a log? It is difficult to understand what went wrong from this screenshot other than ampal was not installed (which seems to be different from the first error you had so I'm assuming we are making progress)

**Comment by universvm** [comment]
@kinal1999 I have pushed our compiled container to docker hub. hope it helps: https://hub.docker.com/r/universvm/timed-design

**Comment by CommunityDiscovery** [comment]
hi! i am still getting the same error. would you be able to assist deploying it on www.healthuniverse.com ?

**Comment by universvm** [comment]
@CommunityDiscovery Have you tried the docker container  https://hub.docker.com/r/universvm/timed-design

**Comment by universvm** [comment]
@kinal1999 Given that there's only 1 pull, ie. mine, for the docker container, I don't think you're following the instructions. I have just tried to pull it on my mac with no issues. My guess is that you're either using a different container or that you're not pulling the correct one from Docker. 

I would be able to help you but please, at least let me know what you tried and the exact error messages, otherwise it is impossible for me to debug.
